name: Run Tests pipeline

on: 
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]
  

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./MVC_API_CoreApp
    - name: Build
      run: dotnet build --no-restore ./MVC_API_CoreApp
      
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Test
      run: dotnet test --no-build --verbosity normal ./MVC_API_CoreApp
